openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                userName:
                  type: string
                email:
                  type: string
                age:
                  type: integer
                password:
                  type: string
              required:
                - firstName
                - lastName
                - userName
                - email
                - age
                - password
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      firstName:
                        type: string
                      lastName:
                        type: string
                      email:
                        type: string
                      age:
                        type: integer
                      userName:
                        type: string
                      password:
                        type: string
        "400":
          description: Invalid request

  /api/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: User login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string

  /api/logout:
    post:
      summary: User logout
      description: Revokes the refresh token and clears authentication cookies.
      responses:
        "200":
          description: Logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged out successfully"
        "500":
          description: Failed to revoke refresh token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to revoke refresh token"

  /api/users/{userId}:
    get:
      summary: Get a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                  email:
                    type: string
                  userName:
                    type: string
                  age:
                    type: integer
        "404":
          description: User not found
    put:
      summary: Update a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                userName:
                  type: string
                age:
                  type: integer
                email:
                  type: string
      responses:
        "200":
          description: User updated successfully
        "400":
          description: Invalid request
        "404":
          description: User not found
    patch:
      summary: Update user password
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
              required:
                - oldPassword
                - newPassword
      responses:
        "200":
          description: Password updated successfully
        "400":
          description: Invalid request
        "401":
          description: Old password is incorrect
        "404":
          description: User not found
        "500":
          description: Failed to hash new password
    delete:
      summary: Delete a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User deleted successfully
        "404":
          description: User not found

  /api/videos:
    post:
      summary: Upload a video
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                videoFile:
                  type: string
                  format: binary
              required:
                - name
                - description
                - videoFile
      responses:
        "200":
          description: Video uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Invalid request or failed to retrieve file
        "401":
          description: User not authenticated
        "500":
          description: Failed to save file

  /api/videos/{videoId}:
    get:
      summary: Get video by ID
      description: Retrieve detailed information about a specific video
      parameters:
        - name: videoId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Video retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  videoId:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  uploaded:
                    type: string
                    format: date-time
                  url:
                    type: string
                    format: uri
                  thumbnail:
                    type: string
                    format: uri
                  likes:
                    type: integer
                  dislikes:
                    type: integer
                  channel:
                    type: string
        "404":
          description: Video not found

  /api/videos/{videoId}/like:
    post:
      summary: Like a video
      security:
        - bearerAuth: []
      parameters:
        - name: videoId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Video liked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  likes:
                    type: integer
        "400":
          description: Invalid request
        "401":
          description: Unauthorized access
        "404":
          description: Video or user not found
        "500":
          description: Failed to update like or link to user

  /api/videos/{videoId}/dislike:
    post:
      summary: Dislike a video
      security:
        - bearerAuth: []
      parameters:
        - name: videoId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Video disliked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  dislikes:
                    type: integer
        "400":
          description: Invalid request
        "401":
          description: Unauthorized access
        "404":
          description: Video or user not found
        "500":
          description: Failed to update dislike or link to user
